spring:
  datasource:
    url : jdbc:mysql://localhost:3306/stock?useUnicode=true&characterEncoding=UTF-8
    username : root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    sql-script-encoding: UTF-8
  jpa:
    database : MYSQL
    show-sql : false
    hibernate:  
      ddl-auto : none
      naming: 
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
          dialect : org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    time-zone : GMT+8
    date-format : yyyy-MM-dd HH:mm:ss
    
restClient:
  connectionTimeout: 15000
  readTimeout: 15000
  connectionRequestTimeout: 200
  maxTotal: 10
  maxPerRoute: 5
   
server:
  port: 8088
logging:
  config: classpath:logback.xml

  